### ISSUE TITLE
Option to Observe/Return entire Response

### ISSUE THREAD

**Issue by resistancecanyon** [flowup/ngx-swagger-client-generator#5]
The generator should have an option from each api function to pass on an option whether to return the entire response for one use case  and/or to return the expected response data.
Currently the response body is what we're getting/observing.

@vmasek @gelidus 
IMO the default value returned should be simplistic as to return the response body alone for most of the use cases.

Expected code snapshot when observing the entire response in 

> private sendRequest 
function

` 
  private sendRequest<T>(method: string, uri: string, headers: HttpHeaders, params: HttpParams, body: any): Observable<HttpResponse<T>> {
    if (method === 'get') {
      return this.http.get<T>(this.domain + uri, { headers: headers.set('Accept', 'application/json'), params: params, observe: 'response' });
    } 
  }
`

**Comment by vmasek** [comment]
Hi, this issue should be resolved by adding support for passing request options as requested in #4 .
Also, there will be default headers and params that can be set to affect each request.

Why do you need the `Response` itself in your use-cases? Currently, we don't need such behavior.

**Comment by gelidus** [comment]
@vmasek I don't see having default headers and params to each request feature needed here, as DI will allow you to replace the service with extended service in case you need such behavior.

**Comment by vmasek** [comment]
@gelidus yes you are right, my answer for headers and params was covering only part of the problem which is setting an `Accept` header

**Comment by vmasek** [comment]
There is a new version out, please test if your request was fulfilled.

**Comment by gelidus** [comment]
@resistancecanyon if you are referring to this request method https://github.com/angular/angular/blob/master/packages/common/http/src/client.ts#L192 , then yes, you will also be able to override the `observe` options on any request when this is integrated.

**Comment by resistancecanyon** [comment]
I'll test it out & let you guys know.
Thanks,
