### ISSUE TITLE
[Enum] generation of wrong enum name

### ISSUE THREAD

**Issue by Layyy** [flowup/ngx-swagger-client-generator#6]
If you have an enum in a separate file it generates correctly but importing it somewhere will cause misnaming it should generate `xxxEnum` but it generates `xxxModel` and even file path is wrong.

**Comment by vmasek** [comment]
Thanks for reporting. This seems like a bigger issue that I've thought. Problem is that generator doesn't have the knowledge about property type signature (model or enum) when being appended to interface properties. 

Will be resolved after refactoring in the near future version.

**Comment by vmasek** [comment]
Resolved by baefa8f
